### PR TITLE
Test, doc and refactoring for _format_phone_number

### PR DESCRIPTION
**Pull request by darnuria**
Added documentation, types, a test to check international number stripping in case of `+33` prefix and a little refactoring because multi-return was not obliged.

Used [black](https://github.com/psf/black) for code formatting of `_format_phone_number` function

### CODE REVIEW

**Comment by darnuria** [comment]
After talking with @djulien19. Where does the need of removing prefix on french numbers come from?

It's not really a major issue, but I am curious, it's coopaname demand? Grap demand? I can ask coopaname people if it was an important detail or if it cause more harm than good.

Exemple:
`+33601460222` will be transformed into: `0601460222`

**Review by robinkeunen — APPROVED** [review]
👍 

For linting, use pre-commit, it's all nicely setup in the repo and uses black.

The specification is [here](https://docs.google.com/document/d/1gExg8d-uFWw_zNjo-xj72CxFgxz-N7xOuXkYVnTJ8wE/edit#heading=h.jsre61isklc0)

**Comment by darnuria** [comment]
Pre-commit: Thanks will checkout that, 


About spec looked into google doc and sharething one look like it's not explicitly specified on our side leaved a comment on "mookup M1".

image

Think it's not a blocking point and we can move on. If any precision is added about that from Coopaname. I would be happy to make a PR if spec is refined on this tiny detail.

[Some edit because got some issue to express what I think without rephrasing multiple time ahah]

**Comment by darnuria** [comment]
Used [pre-commit](https://pre-commit.com/) also rebased. Just if needed OK for squashing if it's our politics with little commits no problem with that. :)

**Comment by robinkeunen** [comment]
👍

**Pull request merged**
