### PR TITLE
[IMP] improve readmes

### PR DESCRIPTION
**Pull request by mclaeysb**
Making readme's more consistent.

Question: it's unclear for me if I can directly write to/edit in `./README.rst`, or if this is somehow generated/overwritten (by the merge bot?)...

### CODE REVIEW

**Review by robinkeunen — APPROVED** [review]
You CAN edit `readme.md` or`readme.rst` et the repo root but you cannot edit `readme.rst` in the modules. I'm still not sure how to use `oca-gen-addons-table` though.

**Comment by mclaeysb** [comment]
documentation on `oca-gen-addons-table` seems hard to find. Maybe @quentinDupont knows more?

**Comment by mclaeysb** [comment]
TIL `oca-gen-addons-table` Thanks @robinkeunen!

**Comment by mclaeysb** [comment]
@robinkeunen you can merge this as well when you'll merge the other PRs

**Pull request merged**
