### PR TITLE
[12.0][IMP] Transport mode Many2Many + french i18n

### PR DESCRIPTION
**Pull request by quentinDupont**
[IMP] Transport mode : Many2Many : one employee can have several transport mode here ;)
image

[IMP] french translation

### CODE REVIEW

**Review by robinkeunen — APPROVED** [review]
Blue bicycle, red bicycle, tricycle, monocycle i guess?

lgtm

**Comment by quentinDupont** [comment]
> Blue bicycle, red bicycle, tricycle, monocycle i guess?
> 
> lgtm

So we can ocabot merge ? :)

**Comment by robinkeunen** [comment]
please do!

**Pull request merged**
