### PR TITLE
[WIP] coopaname_custom: create user and give accounting access rights

### PR DESCRIPTION
**Pull request by robinkeunen**
* res.partner : button to create user and give expense report access
* event.event : create user for all participant to accounting workshop

### CODE REVIEW

**Comment by robinkeunen** [comment]
@mclaeysb 

**done:**
- add a button to partner view
- create user

**not working**
- send email with password reset 
  - inspired from "Grant portal access" and easy_my_coop.models.invoice.create_user
  - I get a "smtp server: connection refused"

**todo:**
- add button to event of type "Atelier Remboursement de Frais"
- this button creates a user for all participant to the event

**Comment by mclaeysb** [comment]
Note: per the specifications, we should also add a link from the partner and employee to that user (field or smart-button?)

**Comment by mclaeysb** [comment]
Took time today to continue on your work @robinkeunen. The `"smtp server: connection refused"` error is normal behaviour apparently when no SMPT outgoing server is set. It passes tests however, and should be ok in production when the servers are set.

I'm not very happy with this code for two points.

1) I'm not very sure about the way I made the button `button_create_user_for_all_participants` conditionally invisible. Is their a way to do this entirely in HTML, without a help-field like `show_button_create_user_for_all_participants`?

2) Since the users/partner/employee structure is not very clean in Odoo*, creating a user from a partner or employee seems messy. 

For starters, at the current state when we create a new user from a partner we just check if a users already exists with that email address. We don't handle the case where multiple users would exist with that email address (but maybe that's just not allowed?) and we don't consult the `partner.user_id` or `user.partner_id` fields (but only use the email address as link). This has some strange effects, for example there's the smart button that counts the amount of users for a partner by checking for similar email, but the action when clicking on it, uses the `[('partner_id', '=', active_id)]` domain filter - and these might give different results.

They main problem lies with employee's, however: when we create a user from an employee (which is a main requirement by our client), that user needs a partner (so one is made when non exists with that email address) but after that, the created users won't remember which employee it was made for (since users don't have an `employee_id` field on users). The count of users for an employee based on the email address works, but the window action doesn't since we can't have a domain `[('employee_id', '=', active_id)]` for users. So right now this window action doesn't work.

How could we solve this? Add a `employee_id` field to users (seems like a big thing for a custom module)? Use a different way of setting the domain filter on the window action, passing the email address for example (I didn't find a way to do use other fields then the `active_id` to set a domain). I'd like to have some other opinions before I get into this. 

* AFAIK in Odoo partner is the most generic, users must have an partner and an email address, and employee's don't have partners - so they are a bit 'outside' partners. And It seems that historically users, partners and employee's were like three main types of contacts

**Comment by robinkeunen** [comment]
## button_create_user_for_all_participants

I did that before, it's not ideal but it works. In a client custom module, you can easily get away with it. Did you try to use `ref` in the domain though? something like:

```
<button [...] attrs="{'invisible': [('type_id', '=', ref("event_type_accounting_workshop")]}"/>
```
or later in the xml
```
<xpath expr="//button[@name='button_create_user_for_all_participants']" position="attributes">
    <attribute name="attrs" eval="{'invisible': [('type_id', '=', ref("event_type_accounting_workshop")]}" />
</xpath>
```

**Comment by robinkeunen** [comment]
## creating a user from a partner

> For starters, at the current state when we create a new user from a partner we just check if a users already exists with that email address. We don't handle the case where multiple users would exist with that email address (but maybe that's just not allowed?) and we don't consult the partner.user_id or user.partner_id fields (but only use the email address as link). This has some strange effects, for example there's the smart button that counts the amount of users for a partner by checking for similar email, but the action when clicking on it, uses the [('partner_id', '=', active_id)] domain filter - and these might give different results.

- if you're talking about the `res_users.email` field, I think the case where a user has several email address, that is several partners is really an edge case that we don't need to take into account for a custom module. Maybe you could just let a note on it in the code or in the _known issues_ of the readme.
- if you're talking about the `res_users.login` field, it is unique for a user, cf base/models/res_users.py:

```
    _sql_constraints = [
        ('login_key', 'UNIQUE (login)',  'You can not have two users with the same login !')
    ]
```

> They main problem lies with employee's, however: when we create a user from an employee (which is a main requirement by our client), that user needs a partner (so one is made when non exists with that email address) but after that, the created users won't remember which employee it was made for (since users don't have an employee_id field on users). The count of users for an employee based on the email address works, but the window action doesn't since we can't have a domain [('employee_id', '=', active_id)] for users. So right now this window action doesn't work.

> How could we solve this? Add a employee_id field to users (seems like a big thing for a custom module)? Use a different way of setting the domain filter on the window action, passing the email address for example (I didn't find a way to do use other fields then the active_id to set a domain). I'd like to have some other opinions before I get into this.


There is a field `employee_ids` in `hr/models/res_users`: 

```
class User(models.Model):
    _inherit = ['res.users']

    employee_ids = fields.One2many('hr.employee', 'user_id', string='Related employees')
```

It is a One2many because the user_id field is defined as a Many2one on the employee model but I'm pretty sure it is unique. I fail to see a case where a user could have several employees. So I think you could use `[('employee_ids, '=', active_id)]` or ` [('employee_ids', '=', [active_id])]` in your action window.

> AFAIK in Odoo partner is the most generic, users must have an partner and an email address, and employee's don't have partners - so they are a bit 'outside' partners. And It seems that historically users, partners and employee's were like three main types of contacts

**Comment by robinkeunen** [comment]
Thank you for finishing the work :-)

... and for being so rigorous!

**Comment by mclaeysb** [comment]
> ## button_create_user_for_all_participants
> Did you try to use `ref` in the domain though? something like:

Tried now, but both of these (would be cool) approaches don't seem to work...

**Comment by mclaeysb** [comment]
> ## creating a user from a partner
> There is a field `employee_ids` in `hr/models/res_users`:
> ... So I think you could use `[('employee_ids, '=', active_id)]` or ` [('employee_ids', '=', [active_id])]` in your action window.

This did the trick! (Along with providing separate xml id's for the two actions)

**Review by mclaeysb — APPROVED** [review]
Yup

**Comment by mclaeysb** [comment]
Note to self: remove TEMP commit before merge! 
This commit disables the forced email sent on user creation, which gives a 111 error in test environment and disabled our manual testing there.

**Comment by mclaeysb** [comment]
Note: new developments coming up!

**Pull request merged**
